import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://coffee-cart.app/');
  
  await page.locator('li').filter({ hasText: 'menu' }).click();
  await page.locator('li').filter({ hasText: 'cart (0)' }).click();
  await page.locator('li').filter({ hasText: 'github' }).click();
  await page.getByLabel('Menu page').click();
  await page.locator('[data-test="Espresso"]').click();
  await expect(page.locator('[data-test="Espresso"]')).toContainText('espresso');
  await page.locator('[data-test="Espresso_Macchiato"]').click();
  await expect(page.locator('[data-test="Espresso_Macchiato"]')).toContainText('milk foam');
  await page.locator('[data-test="Cappuccino"]').click();
  await page.getByRole('button', { name: 'Nah, I\'ll skip.' }).click();
  await expect(page.locator('[data-test="Cappuccino"]')).toContainText('steamed milk');
  await expect(page.locator('[data-test="Cappuccino"]')).toContainText('milk foam');
  await page.locator('[data-test="Mocha"]').click();
  await expect(page.locator('[data-test="Mocha"]')).toContainText('chocolate syrup');
  await page.locator('[data-test="Mocha"]').click();
  await expect(page.locator('[data-test="Mocha"]')).toContainText('steamed milk');
  await page.locator('[data-test="Mocha"]').click();
  await page.getByRole('button', { name: 'Nah, I\'ll skip.' }).click();
  await page.locator('[data-test="Mocha"]').click();
  await expect(page.locator('[data-test="Mocha"]')).toContainText('whipped cream');
  await page.locator('[data-test="Flat_White"]').click();
  await expect(page.locator('[data-test="Flat_White"]')).toContainText('steamed milk');
  await page.locator('[data-test="Americano"]').click();
  await expect(page.locator('[data-test="Americano"]')).toContainText('water');
  await page.locator('[data-test="Cafe_Latte"]').click();
  await expect(page.locator('[data-test="Cafe_Latte"]')).toContainText('steamed milk');
  await expect(page.locator('[data-test="Cafe_Latte"]')).toContainText('milk foam');
  await page.locator('[data-test="Espresso_Con Panna"]').click();
  await expect(page.locator('[data-test="Espresso_Con Panna"]')).toContainText('whipped cream');
  await page.locator('[data-test="Cafe_Breve"]').click();
  await expect(page.locator('[data-test="Cafe_Breve"]')).toContainText('steamed milk');
  await expect(page.locator('[data-test="Cafe_Breve"]')).toContainText('steamed cream');
  await expect(page.locator('[data-test="Cafe_Breve"]')).toContainText('milk foam');
  await page.goto('https://coffee-cart.app/');
});